config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'homes#top'
  get 'homes/admin_top'
  resources :notices, only: [:new, :create, :edit, :show, :update, :destroy]
  post 'orders/confirm'
  get 'orders/complete'
  resources :orders, only: [:new, :create, :show, :update, :destroy]
  delete 'cart_items/destroy_all'
  resources :takeout_items do
     resources :cart_items, only: [:index, :create, :update, :destroy]
  end
  resources :recommendations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  has_many :takeout_items, through: :order_details
  has_many :cart, through: :order_details
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :admin_login, only: [:show, :destroy]

  def new
    @order = Order.new
  end

  def confirm
    @current_cart =current_cart
    @cart_items = current_cart.cart_items.all
    @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }.to_i
    @order = Order.new(order_params)
  end

  def complete
  end

  def create
    @order = Order.new(order_params)
    @order.save!
    @cart_items = current_cart.cart_items.all
    @cart_items.each do |cart_item|
      order_detail = OrderDetail.new
      order_detail.order_id = @order.id
      order_detail.takeout_neme = cart_item.takeout_item.takeout_name
      order_detail.price = cart_item.takeout_item.tax_price
      order_detail.amount = cart_item.amount
      order_detail.save!
      cart_item.delete
    end
    redirect_to orders_complete_path
  end

  def show
    @order = Order.find(params[:id])
  end

  def destroy
    order = Order.find(params[:id])
    order.destroy
    redirect_to homes_admin_top_path
  end

  def order_params
    params.require(:order).permit(:cart_id, :name, :telephone_number, :receipt_datetime, :request, :payment_amount)
  end
   # --------------ログインしていない場合ルートパスに戻る----------------
  def admin_login
    unless signed_in?
      redirect_to root_path
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/complete.html.erb
<div class="container-fluid p-0">
  <div class="under-header"></div>
  <section class="row mx-0", style="height: 100vh;">
    <div class="col-8 p-0 h-100 mx-auto">
      <div class="h-100">
        <h1 class="title d-flex align-items-end justify-content-end", style="height: 40vh;">ご予約完了いたしました</h1>
        <h2 class="middle d-flex align-items-center justify-content-center", style="height: 20vh;">お待ちしております</h2>
        <p class="d-flex justify-content-center"><%= link_to "Topへ戻る", root_path, class: "btn-color" %></p>
      </div>
    </div>
  </section>
</div>

app/views/orders/confirm.html.erb
<div class="container-fluid p-0 background-gradient">
  <div class="under-header"></div>
  <div class="row my-40 mx-0", style="height: 150px;">
    <div class="col-8 p-0 h-100 mx-auto border-bottom border-light">
      <div class="h-100">
        <h1 class="title text-light h-100 d-flex align-items-center justify-content-center">ご予約情報確認</h1>
      </div>
    </div>
  </div>
  <div class="row mx-0">
    <div class="w-60 mx-auto">
      <table>
        <thead class="col-12 border-bottom border-light">
          <th class="col-3"></th>
          <th class="col-3"><p class="text text-light d-flex justify-content-center">商品情報</p></th>
          <th class="col-3"><p class="text text-light d-flex justify-content-center">個数</p></th>
          <th class="col-3"><p class="text text-light d-flex justify-content-center">支払金額</p></th>
        </thead>
        <tbody>
        <% @cart_items.each do |cart_item| %>
          <tr class="border-bottom border-light">
            <td class="my-2"><%= image_tag cart_item.takeout_item.image, size: "300x225" %></td>
            <td><p class="middle pl-2 text-light d-flex justify-content-center"><%= cart_item.takeout_item.takeout_name %></p></td>
            <td><p class="middle text-light d-flex justify-content-center"><%= cart_item.amount %></p></td>
            <td><p class="middle text-light d-flex justify-content-center"><%= cart_item.takeout_item.tax_price %>円</p></td>
            <% (cart_item.sum_of_price).floor.to_s(:delimited) %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row w-80 mx-auto title-margin">
    <span class="col-10 text-right text text-light">商品合計:￥</span><p class="col-2 text text-light"><%= @total.round.to_s(:delimited) %></p>
    <span class="col-10 text-right text text-light">お名前:</span><p class="col-2 text text-light"><%= @order.name %></p>
    <span class="col-10 text-right text text-light">電話番号:</span><p class="col-2 text text-light"><%= @order.telephone_number %></p>
    <span class="col-10 text-right text text-light">受け取り日時:</span><p class="col-2 text text-light"><%= @order.receipt_datetime %></p>
    <span class="col-10 text-right text text-light">ご要望:</span><p class="col-2 text text-light"><%= @order.request %></p>
  </div>
   <div class="row w-80 pb-5 mx-auto">
     <span class="col-4"></span>
    <p class="col-4 title-margin text-center"><%= link_to  "予約情報入力に戻る", new_order_path %></p>
      <%= form_with model: @order, url: orders_path, method: :post do |f| %>
        <%= f.hidden_field :cart_id, :value => @current_cart.id %>
	      <%= f.hidden_field :name, :value => @order.name %>
	      <%= f.hidden_field :telephone_number, :value => @order.telephone_number %>
	      <%= f.hidden_field :receipt_datetime, :value => @order.receipt_datetime %>
	      <%= f.hidden_field :request, :value => @order.request %>
	      <%= f.hidden_field :payment_amount, :value => @total %>
	      <p class="col-4 title-margin text-right">
	        <%= f.submit '注文を確定する', class: "btn-color radius-5" %>
	      </p>
      <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<div class="container-fluid p-0 background-gradient">
  <div class="under-header"></div>
  <div class="row my-40 mx-0", style="height: 150px;">
    <div class="col-8 p-0 h-100 mx-auto border-bottom border-light">
      <div class="h-100">
        <h1 class="title text-light d-flex align-items-center justify-content-center">ご予約情報入力</h1>
        <p class="text mt-3 text-light d-flex align-items-center justify-content-center">「※」がついてる項目は必ずご入力ください。</p>
      </div>
    </div>
  </div>
    <%= form_with model: @order, url: orders_confirm_path, method: :post do |f| %>
      <div class="row w-60 mx-auto mb-5">
        <%= f.label :"※ お名前", class: "light col-4 pr-5 d-flex align-items-center justify-content-end" %>
        <%= f.text_field :name, class: "col-5 form-control", placeholder: "令和道子" %>
      </div>
      <div class="row w-60 mx-auto mb-5">
        <%= f.label :" ※ 電話番号", class: "light col-4 pr-5 d-flex justify-content-end" %>
        <%= f.text_field :telephone_number, class: "col-5 form-control", placeholder: "00000000000" %>
      </div>
      <div class="row w-60 mx-auto">
        <div class="col-4"></div>
        <div class="col-1 px-0 d-flex align-items-center justify-content-end"><p class="light mb-0">年</p></div>
        <div class="col-1 px-0 d-flex align-items-center justify-content-end"><p class="light mb-0">月</p></div>
        <div class="col-1 px-0 mr-3 d-flex align-items-center justify-content-end"><p class="light mb-0">日</p></div>
        <div class="col-1 px-0 d-flex align-items-center justify-content-end"><p class="light mb-0">時</p></div>
        <div class="col-1 px-0 d-flex align-items-center justify-content-end"><p class="light mb-0">分</p></div>
      </div>
      <div class="row w-60 mx-auto mb-5">
        <%= f.label :"※ 受け取り日時", class: "light col-4 pr-5 d-flex align-items-center justify-content-end" %>
        <%= f.datetime_select :receipt_datetime, {:use_month_numbers => true}, class: "col-1 form-control" %>
      </div>
      <div class="row w-60 mx-auto mb-5">
        <%= f.label :"ご要望", class: "light col-4 pr-5 d-flex align-items-center justify-content-end" %>
        <%= f.text_field :request, class: "col-5 form-control", placeholder: "例) 焼肉弁当２つの内１つ大盛にしてください", style: "height: 150px" %>
      </div>
      <div class="row w-60 mx-auto">
        <p class="w-100 title-margin text-right"><%= f.submit "予約情報確認", class: "btn-color radius-5" %></p>
      </div>
    <% end %>
</div>

app/views/orders/show.html.erb
<section class="container-fluid title-margin title-bar">
  <div class="row h-100">
    <div class="col-8 h-100 mx-auto title-textbox">
      <div class="title h-100 d-flex align-items-center justify-content-center"><h1>TAKEOUT予約確認</h1></div>
    </div>
  </div>
</section>

<section class="container my-40">
  <div class="row mb-3">
    <div class="col-3"><p class="text">お名前</p></div>
    <div class="col-9"><p class="middle"><%= @order.name %>様</p></div>
  </div>
  <div class="row mb-3">
    <div class="col-3"><p class="text">お電話番号</p></div>
    <div class="col-9"><p class="middle"><%= @order.telephone_number %></p></div>
  </div>
   <div class="row mb-3">
    <div class="col-3"><p class="text">ご要望</p></div>
    <div class="col-9"><p class="text"><%= @order.request %></p></div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th class="col-3"><p class="text">商品名</p></th>
        <th class="col-3"><p class="text">金額</p></th>
        <th class="col-3"><p class="text">個数</p></th>
        <th class="col-3"><p class="text">合計金額</p></th>
      </tr>
    </thead>
    <tbody>
      <% @order.order_details.each do |order| %>
        <tr>
          <td class="px-3"><p class="text"><%= order.takeout_neme %></p></td>
          <td class="px-3"><p class="text"><%= order.price %>円</p></td>
          <td class="px-3"><p class="text"><%= order.amount %>こ</td>
          <td class="px-3"><p class="text"><%= order.price*order.amount %>円</p></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row mt-5">
    <div class="col-3"><p class="text">お支払金額</p></div>
    <div class="col-9"><p class="middle"><%= @order.payment_amount %>円</p></div>
  </div>
  <div class="row w-100">
     <p class="w-50 title-margin text-center"><%= link_to "戻る", homes_admin_top_path, class: "btn-color" %></p>
    <p class="w-50 title-margin text-center"><%= link_to "削除", order_path(@order.id), method: :delete, class: "btn-delete", "data-confirm" => "本当に削除しますか？"  %></p>
  </div>
</section>