config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'homes#top'
  get 'homes/admin_top'
  resources :notices, only: [:new, :create, :edit, :show, :update, :destroy]
  post 'orders/confirm'
  get 'orders/complete'
  resources :orders, only: [:new, :create, :show, :update, :destroy]
  delete 'cart_items/destroy_all'
  resources :takeout_items do
     resources :cart_items, only: [:index, :create, :update, :destroy]
  end
  resources :recommendations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :recommendations
  has_many :order_details, through: :orders
  has_many :takeout_items
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :admin_login, only: [:admin_top]

  def top
    @foods = Recommendation.order(created_at: :DESC).limit(4)
    @takeout_items = TakeoutItem.order(is_active: :asc).order(created_at: :DESC).limit(3)
    @notices = Notice.order(created_at: :DESC).limit(3)
  end

  def admin_top
    @orders = Order.order(created_at: :DESC)
  end

  private
# --------------ログインしていない場合ルートパスに戻る----------------
  def admin_login
    unless signed_in?
      redirect_to root_path
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/admin_top.html.erb
<section class="container-fluid title-margin title-bar">
  <div class="row h-100">
    <div class="col-8 h-100 mx-auto title-textbox">
      <div class="title h-100 d-flex align-items-center justify-content-center"><h1>管理者Top</h1></div>
    </div>
  </div>
</section>

<div class="container">
  <div class="row">
    <section class="col-sm-6">
      <h2 class="middle">TAKEOUT予約</h2>
        <div class="my-40">
        <% @orders.each do |order| %>
          <%=link_to order_path(order.id) do %>
            <div class="card mb-3">
              <div class="row">
                <div class="col-12">
                  <p class="card-title middle text-center my-3"><%= order.name %>様</p>
                  <p class="card-title text text-center my-3"><%= order.receipt_datetime %></p>
                </div>
              </div>
              <div class="card-body">
                <% order.order_details.each do |order_detail| %>
                  <div class="row">
                    <div class="col-6"><p class="card-text text"><%= order_detail.takeout_neme %></p></div>
                    <div class="col-6"><p class="card-text text"><%= order_detail.amount %>つ</p></div>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </section>

    <section class="col-sm-6">
      <div class="m-5">
        <%=link_to "Menu管理画面へ", new_recommendation_path, class: "col-10 btn btn-outline-success btn-lg my-4" %>
        <%=link_to "Takeout管理画面へ", new_takeout_item_path, class: "col-10 btn btn-outline-success btn-lg my-4" %>
        <%=link_to "お知らせ管理画面へ", new_notice_path, class: "col-10 btn btn-outline-success btn-lg my-4" %>
      </div>
    </section>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container-fluid p-0 mx-0">
<!--------------------------<ここからTop画面>---------------------------------->
  <section class="row relative">
    <div class="col-6 top-image"></div>
    <div class="col-6 top-image"></div>
    <div class="top-textbox">
      <div class="title h-100 d-flex align-items-center justify-content-center"><h1>ねむび屋</h1></div>
    </div>
  </section>

  <div class="p-0 background-gradient">
  <!--------------------------<ここからabout画面>---------------------------------->
    <section class="row w-85 mx-auto about-padding">
      <div class="col-sm-6">
        <h2 class="title text-light mb-5"><a name="about">About</a></h2>
        <h3 class="middle text-light mb-5">韓国風居酒屋ねむび屋</h3>
        <p class="text small text-light">
         「韓国料理風居酒屋ねむび屋」は、鍋、肉料理、<br>
           韓国料理を楽しめるお店です。<br><br>
           お肉はこだわりの最高級のものをそろえ、そのときにあった<br>
           食べ方でお楽しみいただけます。また、お鍋は様々な<br>
           トッピングができ自分の好みでカスタマイズを<br>
           していただくことが可能です。<br><br>
           お席はおひとり様でもご利用しやすいカウンターから、<br>
           テーブル席(喫煙席３席)、に加え大人数でもご利用できる<br>
           お座敷もあります。<br>
           全45席で貸し切りも可能です。ご相談ください。<br>
        </p>
      </div>
      <div class="col-sm-6 mt-3">
        <%= image_tag "cropPAKS_BISTROtennai.jpg", class: "w-85"%>
      </div>
    </section>

<!--------------------------<ここからrecommendeation画面>---------------------------------->
    <section class="row my-40 mx-0 title-bar">
      <a name="recommends"></a>
      <div class="col-8 p-0 h-100 mx-auto title-image-recommendation">
        <div class="h-100 sub-title">
          <div class="title h-100 d-flex align-items-center justify-content-center"><h1>今月のおすすめ</h1></div>
        </div>
      </div>
    </section>
    <div class="row w-60 mx-auto mb-140">
      <ul class="w-100">
        <li class="text text-light d-flex justify-content-center">おすすめ料理を４品選んでご紹介しています。</li>
        <li class="text small text-light d-flex justify-content-center">※仕入れ状況により提供できない場合があります。</li>
      </ul>
    </div>
    <section class="row w-60 mx-auto">
      <div class="w-100">
        <% @foods.each.with_index(1) do |food,i| %>
          <% if i.odd? %>
            <div class="row border-bottom border-light">
              <div class="col-5 pt-4 pl-5 pr-0"><%= image_tag food.image, size: "400x300" %></div>
              <div class="col-1 px-0"></div>
              <div class="col-6 pt-5 px-0">
                <p class="middle text-light d-flex justify-content-center"><%= food.name %></p>
                <p class="text text-light d-flex justify-content-center"><%= food.tax_price %>円</p>
                <p class="text small text-light d-flex justify-content-center"><%= food.details %></p>
              </div>
            </div>
          <% else %>
           <div class="row border-bottom border-light">
              <div class="col-6 pt-5 px-0">
                <p class="middle text-light d-flex justify-content-center"><%= food.name %></p>
                <p class="text text-light d-flex justify-content-center"><%= food.tax_price %>円</p>
                <p class="text small text-light  d-flex justify-content-center"><%= food.details %></p>
              </div>
              <div class="col-1 px-0"></div>
              <div class="col-5 pt-4 px-0"><%= image_tag food.image, size: "400x300" %></div>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="row w-100">
        <p class="w-100 title-margin text-right"><%= link_to "メニューを見る", recommendations_path, class: "btn-color" %></p>
      </div>
    </section>

<!--------------------------<ここからtakeout画面>---------------------------------->
    <section class="row my-40 mx-0 title-bar">
      <a name="takeout"></a>
      <div class="col-8 p-0 h-100 mx-auto title-image-takeout">
        <div class="h-100 sub-title">
          <div class="title h-100 d-flex align-items-center justify-content-center"><h1>TAKEOUT</h1></div>
        </div>
      </div>
    </section>
    <div class="row w-60 mx-auto mb-140">
      <ul class="w-100">
        <li class="text text-light d-flex justify-content-center">
          このサイトでは、下記の「TAKEOUT商品を見る」ボタンからTAKEOUTのご予約ができます。<br>
          また、お電話でのご予約も可能です。</li>
        <li class="mt-3 text small text-light d-flex justify-content-center">電話番号　00-0000-0000</li>
      </ul>
    </div>
    <section class="takeout-back my-80">
      <div class="row w-85 mx-auto">
        <% @takeout_items.each do |takeout_item| %>
          <div class="col-4">
            <%= image_tag takeout_item.image, size: "360x270" %>
            <p class="middle text-light "><%= takeout_item.takeout_name %></p>
            <p class="text text-light"><%= takeout_item.tax_price %>円</p>
          </div>
        <% end %>
      </div>
      <div class="row w-100">
        <p class="w-100 title-margin text-center"><%= link_to "TAKEOUT商品を見る", takeout_items_path, class: "btn-color" %></p>
      </div>
    </section>

    <hr class="m-0 bg-light">
    <a name="notice"></a>

<!--------------------------<ここからnotice画面>---------------------------------->
    <section class="row  mx-0 my-40">
      <div class="col-8 p-0 h-100 mx-auto">
        <div class="title text-light h-100 d-flex align-items-center justify-content-center"><h1>お知らせ</h1></div>
      </div>
    </section>
    <section class="row w-85 mx-auto">
      <div class="row w-100 mx-0 my-40">
        <% @notices.each do |notice| %>
          <%= link_to notice_path(notice.id), class: "row col-12 p-0 text-dark" do  %>
            <div class="card w-100 mb-3">
              <div class="card-body">
                <div class="row">
                  <h3 class="middle col-9"><%= notice.title %></h3>
                  <p class="text col-3 d-flex align-items-center justify-content-center"><small><%= notice.updated_at %></small></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="row w-100 mx-0 mb-140">
        <p class="w-100 title-margin text-center"><%= link_to "Topへ戻る", root_path, class: "btn-color" %></p>
      </div>
    </section>
  </div>
</div>