config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'homes#top'
  get 'homes/admin_top'
  resources :notices, only: [:new, :create, :edit, :show, :update, :destroy]
  post 'orders/confirm'
  get 'orders/complete'
  resources :orders, only: [:new, :create, :show, :update, :destroy]
  delete 'cart_items/destroy_all'
  resources :takeout_items do
     resources :cart_items, only: [:index, :create, :update, :destroy]
  end
  resources :recommendations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :takeout_item
  belongs_to :cart

  def sum_of_price
    takeout_item.tax_price * amount
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @cart_items = current_cart.cart_items.all
    @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }.to_i
  end

  def create
    cart = current_cart
    takeout_item = TakeoutItem.find(params[:takeout_item_id])
    @buy_item = cart.add_takeout_item(takeout_item.id)
    unless @buy_item.amount
      @buy_item.amount = 0
    end
    @buy_item.amount += cart_item_params[:amount].to_i
    @buy_item.save
    redirect_to takeout_item_cart_items_path
  end

  def destroy
    buy_item = CartItem.find(params[:id])
    buy_item.destroy
    redirect_to takeout_item_cart_items_path
  end

  def destroy_all
    cart = current_cart
    cart.cart_items.destroy_all
    redirect_to takeout_item_cart_items_path(cart.id)
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:amount)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="container-fluid p-0 background-gradient">
  <div class="under-header"></div>
  <section class="row my-40 mx-0 title-bar">
    <div class="col-8 p-0 h-100 mx-auto title-image-cart">
      <div class="h-100 sub-title">
        <h1 class="title h-100 d-flex align-items-center justify-content-center">CART </h1>
      </div>
    </div>
  </section>

  <section class="row mx-0">
    <div class="w-60 mx-auto">
      <table>
        <thead class="col-12 border-bottom border-light">
          <th class="col-3"></th>
          <th class="col-3"><p class="text text-light d-flex justify-content-center">商品情報</p></th>
          <th class="col-2"><p class="text text-light d-flex justify-content-center">個数</p></th>
          <th class="col-2"><p class="text text-light d-flex justify-content-center">支払金額</p></th>
          <th class="col-2"></th>
        </thead>
        <tbody>
        <% @cart_items.each do |cart_item| %>
          <tr class="border-bottom border-light">
            <td class="my-2"><%= image_tag cart_item.takeout_item.image, size: "300x225" %></td>
            <td class="ml-2"><p class="middle pl-3 text-light d-flex justify-content-center"><%= cart_item.takeout_item.takeout_name %></p></td>
            <td><p class="middle text-light d-flex justify-content-center"><%= cart_item.amount %></p></td>
            <td><p class="middle text-light d-flex justify-content-center"><%= cart_item.takeout_item.tax_price %>円</p></td>
            <td><%= link_to "削除", takeout_item_cart_item_path(cart_item.takeout_item_id, cart_item.id), method: :delete, class: 'btn-delete' %></td>
            <% (cart_item.sum_of_price).floor.to_s(:delimited) %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </section>

  <div class="row w-80 mx-auto">
    <p class="w-100 title-margin text-right"><%= link_to  "カートの中身を空にする", cart_items_destroy_all_path, method: :delete, class: 'btn-delete radius-5' %></p>
  </div>

  <div class="row w-80 mx-auto">
    <span class="col-12 title-margin text-right"><p class="text text-light">商品合計:￥<%= @total.round.to_s(:delimited)  %></p></span>
  </div>

  <div class="row w-80 mx-auto", style="padding-bottom: 50px;">
     <span class="col-4"></span>
    <p class="col-4 title-margin text-center"><%= link_to  "買い物に戻る", takeout_items_path%></p>
    <p class="col-4 title-margin text-right"><%= link_to  "予約情報入力", new_order_path, class: 'btn-color radius-5' %></p>
  </div>
</div>