config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'homes#top'
  get 'homes/admin_top'
  resources :notices, only: [:new, :create, :edit, :show, :update, :destroy]
  post 'orders/confirm'
  get 'orders/complete'
  resources :orders, only: [:new, :create, :show, :update, :destroy]
  delete 'cart_items/destroy_all'
  resources :takeout_items do
     resources :cart_items, only: [:index, :create, :update, :destroy]
  end
  resources :recommendations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :takeout_items, through: :cart_items
  has_many :order_details

  def add_takeout_item(item_id)
    cart_items.find_or_initialize_by(takeout_item_id: item_id)
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :takeout_item
  belongs_to :cart

  def sum_of_price
    takeout_item.tax_price * amount
  end
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :recommendations
  has_many :order_details, through: :orders
  has_many :takeout_items
end

app/models/notice.rb
class Notice < ApplicationRecord
  validates :title, presence: true
  validates :notice_details, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  has_many :takeout_items, through: :order_details
  has_many :cart, through: :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :cart, optional: true
  has_many :takeout_items

  def sum_of_price
    price * price
  end
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  has_one_attached :image
  belongs_to :home, optional: true

  validates :image, presence: true
  validates :name, presence: true
  validates :details, presence: true
  validates :tax_price, presence: true
end

app/models/takeout_item.rb
class TakeoutItem < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
  belongs_to :home, optional: true
  belongs_to :order_detail, optional: true

  validates :image, presence: true
  validates :takeout_name, presence: true
  validates :takeout_details, presence: true
  validates :tax_price, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def my_cart
    # @cart_items = current_cart.cart_items.includes([:product])
    # @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :admin_login, only: [:admin_top]

  def top
    @foods = Recommendation.order(created_at: :DESC).limit(4)
    @takeout_items = TakeoutItem.order(is_active: :asc).order(created_at: :DESC).limit(3)
    @notices = Notice.order(created_at: :DESC).limit(3)
  end

  def admin_top
    @orders = Order.order(created_at: :DESC)
  end

  private
# --------------ログインしていない場合ルートパスに戻る----------------
  def admin_login
    unless signed_in?
      redirect_to root_path
    end
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
before_action :admin_login, only: [:new, :create, :edit, :update, :destroy,]

  def new
    @notice = Notice.new
    @notices = Notice.order(created_at: :DESC)
  end

  def create
    @notice = Notice.new(notices_params)
    if @notice.save
      redirect_to edit_notice_path(@notice.id)
    else
      @notices = Notice.all
      render :new
    end
  end

  def edit
    @notice = Notice.find(params[:id])
  end

  def update
    notice = Notice.find(params[:id])
    notice.update(notices_params)
    redirect_to new_notice_path
  end

  def show
    @notice = Notice.find(params[:id])
  end

  def destroy
    notice = Notice.find(params[:id])
    notice.destroy
    redirect_to new_notice_path
  end

  private

  def notices_params
    params.require(:notice).permit(:title, :notice_details)
  end
  # --------------ログインしていない場合ルートパスに戻る----------------
  def admin_login
    unless signed_in?
      redirect_to root_path
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :admin_login, only: [:show, :destroy]

  def new
    @order = Order.new
  end

  def confirm
    @current_cart =current_cart
    @cart_items = current_cart.cart_items.all
    @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }.to_i
    @order = Order.new(order_params)
  end

  def complete
  end

  def create
    @order = Order.new(order_params)
    @order.save!
    @cart_items = current_cart.cart_items.all
    @cart_items.each do |cart_item|
      order_detail = OrderDetail.new
      order_detail.order_id = @order.id
      order_detail.takeout_neme = cart_item.takeout_item.takeout_name
      order_detail.price = cart_item.takeout_item.tax_price
      order_detail.amount = cart_item.amount
      order_detail.save!
      cart_item.delete
    end
    redirect_to orders_complete_path
  end

  def show
    @order = Order.find(params[:id])
  end

  def destroy
    order = Order.find(params[:id])
    order.destroy
    redirect_to homes_admin_top_path
  end

  def order_params
    params.require(:order).permit(:cart_id, :name, :telephone_number, :receipt_datetime, :request, :payment_amount)
  end
   # --------------ログインしていない場合ルートパスに戻る----------------
  def admin_login
    unless signed_in?
      redirect_to root_path
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/takeout_items_helper.rb
module TakeoutItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>neambiya</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="robots" content="noindex">
  </head>

  <body>
    <div class="content">
      <header>
        <nav class="navbar navbar-expand-lg header-color">
          <a class="navbar-brand" href="/">
            <span class="header-text middle">ねむび屋</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse"
           data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "管理者Home", homes_admin_top_path, class: 'text nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "Menu管理", new_recommendation_path, class: 'text nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "Takeout管理", new_takeout_item_path, class: 'text nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "News管理", new_notice_path, class: 'text nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'text nav-link' %>
                </li>
              <% else %>
                <li class="nav-item ml-4">
                  <a class="navbar-brand" href="/">
                    <span class="text nav-link">Home</span>
                  </a>
                <li class="nav-item ml-4">
                  <a class="navbar-brand" href="/#about">
                    <span class="text nav-link">About</span>
                  </a>
                </li>
                <li class="nav-item ml-4">
                 <a class="navbar-brand" href="/#recommends">
                    <span class="text nav-link">Menu</span>
                  </a>
                </li>
                <li class="nav-item ml-4">
                 <a class="navbar-brand" href="/#takeout">
                    <span class="text nav-link">Takeout</span>
                  </a>
                </li>
                <li class="nav-item mx-4">
                  <a class="navbar-brand" href="/#notice">
                    <span class="text nav-link">News</span>
                  </a>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </header>
      <main>
        <% flash.each do |message_type, message| %>
          <p id="<%= message_type %>"><%= message %></p>
        <% end %>
        <%= yield %>
      </main>
    </div>

    <footer>
      <div class="container-fluid py-3 footer-color">
        <div class="row">
          <div class="text small mx-auto">
            <p>ねむび屋</p>
          </div>
        </div>
        <div class="row">
          <div class="text small mx-auto">
            <p>大阪府大阪市住之江区中加賀屋99-99-99</p>
          </div>
        </div>
        <div class="row">
          <div class="text small mx-auto">
            <p>営業時間　17:00～23:00</p>
            <p>定休日　月曜</p>
          </div>
        </div>
        <div class="row">
          <div class="text small mx-auto">
            <p>電話番号　00-0000-0000</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>